FROM node:20-alpine

WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --production

# Copy source
COPY . .

# Expose Express port
EXPOSE 8080

# Start server
CMD ["node", "index.js"]
